name: "Build, Test & Deploy"

on:
  push:
    branches: [master, main]

env:
  PROJECT_VERSION: "1.0.0"

jobs:
  build-cache: 
    runs-on: ubuntu-latest
    name: "Build and Cache Dependencies"
    steps: 
      - name: "Set up JDK 17"
        uses: actions/setup-java@4.5.0
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: "Build project"
        run: mvn clean package -DskipTests -Djar.filename=helloworld-$PROJECT_VERSION.jar

      - name: "Load cache"
        uses: actions/cache@4.1.2
        with:
          path: "/maven-cache/libs"
        
